/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-bright': '#39393e',
        'on-surface-variant': '#c7c5d0',
        'outline': '#91909a',
        'on-error-container': '#ffdad6',
        'on-secondary-container': '#ceaaf0',
        'on-primary-fixed': '#101549',
        'surface-tint': '#bdc2ff',
        'inferred-amber': '#fbbf24',
        'surface': '#131318',
        'background': '#131318',
        'error': '#ffb4ab',
        'on-primary': '#262b5e',
        'primary-container': '#bdc2ff',
        'obsidian-deep': '#0a0a0f',
        'surface-dim': '#131318',
        'surface-container-high': '#2a292f',
        'on-background': '#e4e1e8',
        'tertiary-fixed-dim': '#f7bd3e',
        'surface-variant': '#35343a',
        'surface-container-low': '#1b1b20',
        'on-tertiary-fixed-variant': '#5d4200',
        'inverse-primary': '#555a90',
        'confirmed-emerald': '#34d399',
        'primary': '#dfe0ff',
        'primary-fixed-dim': '#bdc2ff',
        'surface-container': '#1f1f24',
        'primary-fixed': '#dfe0ff',
        'inverse-surface': '#e4e1e8',
        'on-primary-fixed-variant': '#3d4276',
        'on-surface': '#e4e1e8',
        'on-secondary': '#40215d',
        'surface-container-highest': '#35343a',
        'on-secondary-fixed-variant': '#573976',
        'tertiary-fixed': '#ffdea4',
        'surface-glass': 'rgba(26, 26, 40, 0.7)',
        'tertiary': '#ffdea3',
        'secondary-container': '#5a3b78',
        'on-primary-container': '#494e83',
        'secondary': '#ddb8ff',
        'on-secondary-fixed': '#290947',
        'inverse-on-surface': '#303035',
        'outline-variant': '#46464f',
        'on-tertiary': '#412d00',
        'info-sky': '#60a5fa',
        'unknown-rose': '#f87171',
        'error-container': '#93000a',
        'on-tertiary-fixed': '#261900',
        'secondary-fixed': '#f0dbff',
        'surface-container-lowest': '#0e0e13',
        'tertiary-container': '#f7bd3e',
        'on-error': '#690005',
        'secondary-fixed-dim': '#ddb8ff',
        'on-tertiary-container': '#6b4d00'
      },
      fontFamily: {
        'label-caps': ['JetBrains Mono', 'monospace'],
        'headline-md': ['Playfair Display', 'serif'],
        'headline-lg': ['Playfair Display', 'serif'],
        'headline-sm': ['Playfair Display', 'serif'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
        'code-sm': ['JetBrains Mono', 'monospace'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
