"""
Reverse ADR Generator — converts a synthesized QueryResponse into a
standards-compliant Markdown Architectural Decision Record (MADR format).

MADR spec: https://adr.github.io/madr/
"""

from __future__ import annotations

import re
from datetime import datetime
from typing import Optional


_SLUG_RE = re.compile(r"[^a-z0-9]+")


def _slugify(text: str, max_len: int = 50) -> str:
    """Convert title text to a safe filename slug."""
    slug = _SLUG_RE.sub("-", text.lower()).strip("-")
    return slug[:max_len].strip("-")


def generate_adr(
    question: str,
    answer: str,
    citations: list[dict],
    confidence_summary: str,
    title: Optional[str] = None,
) -> tuple[str, str]:
    """
    Generate a MADR-format Architecture Decision Record from a Continuum response.

    Returns:
        (filename, markdown_content)
        filename: e.g. "0001-why-hooks-were-introduced.md"
        markdown_content: Full MADR markdown string
    """
    adr_title = title or _derive_title(question)
    slug = _slugify(adr_title)
    filename = f"adr-{slug}.md"
    date_str = datetime.utcnow().strftime("%Y-%m-%d")

    # Map confidence to MADR status
    status_map = {
        "strong_evidence": "Accepted",
        "partial_evidence": "Accepted (Partial Evidence)",
        "insufficient_evidence": "Deprecated — Insufficient Evidence",
    }
    status = status_map.get(confidence_summary, "Proposed")

    # Separate citations by confidence
    confirmed = [c for c in citations if c.get("confidence") == "confirmed"]
    inferred = [c for c in citations if c.get("confidence") == "inferred"]
    unknown = [c for c in citations if c.get("confidence") == "unknown"]

    # Build MADR sections
    lines = [
        f"# {adr_title}",
        "",
        f"Date: {date_str}",
        "",
        f"Status: {status}",
        "",
        "## Context and Problem Statement",
        "",
        f"> {question}",
        "",
        "This decision record was auto-generated by **Continuum — Decision Archaeology** "
        "from GitHub PR/issue history.",
        "",
        "## Decision Outcome",
        "",
        answer,
        "",
    ]

    # Confirmed evidence
    if confirmed:
        lines += [
            "## Confirmed Evidence",
            "",
            "> These claims are **explicitly stated** in the source artifacts.",
            "",
        ]
        for c in confirmed:
            author_part = f" — *@{c['author']}*" if c.get("author") else ""
            quote_part = f"\n  > {c['quote']}" if c.get("quote") else ""
            lines += [
                f"- **{c['text']}**{author_part}",
                f"  [{c['source_type'].upper()} #{c['source_id']}]({c['source_url']}){quote_part}",
                "",
            ]

    # Inferred evidence
    if inferred:
        lines += [
            "## Inferred Evidence",
            "",
            "> These claims are **reasonably deduced** from context but not explicitly stated.",
            "",
        ]
        for c in inferred:
            lines += [
                f"- *{c['text']}*",
                f"  [{c['source_type'].upper()} #{c['source_id']}]({c['source_url']})",
                "",
            ]

    # Unknown / gaps
    if unknown:
        lines += [
            "## Evidence Gaps",
            "",
            "> These claims could **not be verified** from available records.",
            "",
        ]
        for c in unknown:
            lines += [
                f"- ❓ {c['text']}",
                "",
            ]

    lines += [
        "## Sources",
        "",
        "_Auto-generated by [Continuum](https://github.com/Monish-D609/continuum-decision-archaeology) "
        "from indexed GitHub history._",
        "",
    ]

    all_source_urls = list({c["source_url"]: c for c in citations}.values())
    for c in all_source_urls:
        lines.append(f"- [{c['source_type'].upper()} #{c['source_id']}]({c['source_url']})")

    return filename, "\n".join(lines)


def _derive_title(question: str) -> str:
    """Derive a short ADR title from the question."""
    # Strip leading "why ", "what ", "how " etc.
    q = question.strip().rstrip("?")
    prefixes = ["why was ", "why were ", "why is ", "why did ", "what was ", "how was ", "when was "]
    q_lower = q.lower()
    for prefix in prefixes:
        if q_lower.startswith(prefix):
            q = q[len(prefix):]
            break
    # Capitalize first letter
    return q[:80].strip().capitalize() if q else question[:80]
